name: My first worflow
on: push
jobs:
  fist_job:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Repo
      uses: actions/checkout@v4 
    - name: List and Read files
      run: |
        echo "My first gh actions job"
        ls -lrta
        cat README.md
    # - name: List Files
    #   run: ls

    # - name: Read
    #   run: cat README.md
    
    - name: Generate ASCII network
      run: cowsay -f dragon "Run for cover, I AM A DRAGON.... RARR" >> dragon.txt