name: My firsy worflow
on: push
jobs:
  fist_job:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Repo
      uses: actions/checkout@v4 
    - name: Welcome
      run: echo "My first gh actions job"

    - name: List Files
      run: ls

    - name: Read
      run: cat README.md