name: Exploring variables and secrets
on: 
  schedule:
    - cron: "*/1 * * * *"

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker build
      run: echo docker build -t docker.io/{{ vars.DOCKERUSERNAME }}/imagename:latest
    
    - name: Docker login
      run: echo docker login --username={{ vars.DOCKERUSERNAME }} --password={{ secrets.PASS}}
